// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kvxDl53T9m5Sy8xgLNpvKBfKFdCcBkg',
    appId: '1:114433765139:web:ee5b2c6c3d20c34f5734e6',
    messagingSenderId: '114433765139',
    projectId: 'smart-medicine-dispenser-efa5b',
    authDomain: 'smart-medicine-dispenser-efa5b.firebaseapp.com',
    storageBucket: 'smart-medicine-dispenser-efa5b.firebasestorage.app',
    measurementId: 'G-9SCHWEK8GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKCcVJaB92HSbh6d9CFAQFVDNMPiFRTY',
    appId: '1:114433765139:android:daac27817247da365734e6',
    messagingSenderId: '114433765139',
    projectId: 'smart-medicine-dispenser-efa5b',
    storageBucket: 'smart-medicine-dispenser-efa5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaESwDtLKOWRv3ybhbfsX0zyX5dM6qa2c',
    appId: '1:114433765139:ios:adb60244d51e2a0f5734e6',
    messagingSenderId: '114433765139',
    projectId: 'smart-medicine-dispenser-efa5b',
    storageBucket: 'smart-medicine-dispenser-efa5b.firebasestorage.app',
    iosBundleId: 'com.example.smartMedicineDispenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaESwDtLKOWRv3ybhbfsX0zyX5dM6qa2c',
    appId: '1:114433765139:ios:adb60244d51e2a0f5734e6',
    messagingSenderId: '114433765139',
    projectId: 'smart-medicine-dispenser-efa5b',
    storageBucket: 'smart-medicine-dispenser-efa5b.firebasestorage.app',
    iosBundleId: 'com.example.smartMedicineDispenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kvxDl53T9m5Sy8xgLNpvKBfKFdCcBkg',
    appId: '1:114433765139:web:8356f2986e6179a55734e6',
    messagingSenderId: '114433765139',
    projectId: 'smart-medicine-dispenser-efa5b',
    authDomain: 'smart-medicine-dispenser-efa5b.firebaseapp.com',
    storageBucket: 'smart-medicine-dispenser-efa5b.firebasestorage.app',
    measurementId: 'G-PX8ZXKXPHG',
  );
}
